version: '3.8'
services:
  anaconda:
    image: continuumio/anaconda3
    container_name: anaconda_dev
    volumes:
      - ./notebooks:/opt/notebooks
      - ./envs:/opt/conda/envs
    ports:
      - "8888:8888"
      - "4040:4040" 
    environment:
      - JUPYTER_TOKEN=my-secure-password
    command: /bin/bash -c "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"

# http://127.0.0.1:8888/tree?token=5adb1ac4f18307813f3021911139a1e32ef411d84dfa1ab7